(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '\/SGL_Sismored\/Sismored 4.0\/New_telemetry_model' *)
(* @OBJECTFLAGS := '0, 8' *)
(* @SYMFILEFLAGS := '2048' *)
FUNCTIONBLOCK Dev7SJ6x0
VAR_INPUT
	xFirstCycle : BOOL;
iSequenceOrder : INT;
sProtocol : STRING;
eState : eStates;
wMeasure1, wMeasure2, wMeasure3, wMeasure4, wMeasure5, wMeasure6, wMeasure7, wMeasure8, wMeasure9, wMeasure10, wMeasure11: WORD;
xSaveMeasure1, xSaveMeasure2, xSaveMeasure3, xSaveMeasure4, xSaveMeasure5, xSaveMeasure6, xSaveMeasure7, xSaveMeasure8, xSaveMeasure9, xSaveMeasure10, xSaveMeasure11: BOOL;
sNameMeasure1, sNameMeasure2, sNameMeasure3, sNameMeasure4, sNameMeasure5, sNameMeasure6, sNameMeasure7, sNameMeasure8, sNameMeasure9, sNameMeasure10, sNameMeasure11: STRING;
xState1, xState2, xState3, xState4, xState5, xState6, xState7, xState8, xState9, xState10, xState11, xState12, xState13, xState14, xState15, xState16, xState17, xState18, xState19, xState20, xState21, xState22, xState23, xState24, xState25, xState26, xState27, xState28, xState29, xState30, xState31, xState32, xState33, xState34, xState35, xState36, xState37, xState38, xState39, xState40, xState41, xState42, xState43, xState44, xState45, xState46, xState47, xState48: BOOL;
xSaveState1, xSaveState2, xSaveState3, xSaveState4, xSaveState5, xSaveState6, xSaveState7, xSaveState8, xSaveState9, xSaveState10, xSaveState11, xSaveState12, xSaveState13, xSaveState14, xSaveState15, xSaveState16, xSaveState17, xSaveState18, xSaveState19, xSaveState20, xSaveState21, xSaveState22, xSaveState23, xSaveState24, xSaveState25, xSaveState26, xSaveState27, xSaveState28, xSaveState29, xSaveState30, xSaveState31, xSaveState32, xSaveState33, xSaveState34, xSaveState35, xSaveState36, xSaveState37, xSaveState38, xSaveState39, xSaveState40, xSaveState41, xSaveState42, xSaveState43, xSaveState44, xSaveState45, xSaveState46, xSaveState47, xSaveState48: BOOL;
sNameState1, sNameState2, sNameState3, sNameState4, sNameState5, sNameState6, sNameState7, sNameState8, sNameState9, sNameState10, sNameState11, sNameState12, sNameState13, sNameState14, sNameState15, sNameState16, sNameState17, sNameState18, sNameState19, sNameState20, sNameState21, sNameState22, sNameState23, sNameState24, sNameState25, sNameState26, sNameState27, sNameState28, sNameState29, sNameState30, sNameState31, sNameState32, sNameState33, sNameState34, sNameState35, sNameState36, sNameState37, sNameState38, sNameState39, sNameState40, sNameState41, sNameState42, sNameState43, sNameState44, sNameState45, sNameState46, sNameState47, sNameState48: STRING;
byRiseState1, byRiseState2, byRiseState3, byRiseState4, byRiseState5, byRiseState6, byRiseState7, byRiseState8, byRiseState9, byRiseState10, byRiseState11, byRiseState12, byRiseState13, byRiseState14, byRiseState15, byRiseState16, byRiseState17, byRiseState18, byRiseState19, byRiseState20, byRiseState21, byRiseState22, byRiseState23, byRiseState24, byRiseState25, byRiseState26, byRiseState27, byRiseState28, byRiseState29, byRiseState30, byRiseState31, byRiseState32, byRiseState33, byRiseState34, byRiseState35, byRiseState36, byRiseState37, byRiseState38, byRiseState39, byRiseState40, byRiseState41, byRiseState42, byRiseState43, byRiseState44, byRiseState45, byRiseState46, byRiseState47, byRiseState48: BYTE;
xCommand1, xCommand2, xCommand3, xCommand4, xCommand5, xCommand6, xCommand7, xCommand8, xCommand9: BOOL;
xSaveCommand1, xSaveCommand2, xSaveCommand3, xSaveCommand4, xSaveCommand5, xSaveCommand6, xSaveCommand7, xSaveCommand8, xSaveCommand9: BOOL;
sNameCommand1, sNameCommand2, sNameCommand3, sNameCommand4, sNameCommand5, sNameCommand6, sNameCommand7, sNameCommand8, sNameCommand9: STRING;
xTriggerCommand1, xTriggerCommand2, xTriggerCommand3, xTriggerCommand4, xTriggerCommand5, xTriggerCommand6, xTriggerCommand7, xTriggerCommand8, xTriggerCommand9: BOOL;

END_VAR
VAR_OUTPUT
	wMeasureOutput1, wMeasureOutput2, wMeasureOutput3, wMeasureOutput4, wMeasureOutput5, wMeasureOutput6, wMeasureOutput7, wMeasureOutput8, wMeasureOutput9, wMeasureOutput10, wMeasureOutput11: WORD;
xStateOutput1, xStateOutput2, xStateOutput3, xStateOutput4, xStateOutput5, xStateOutput6, xStateOutput7, xStateOutput8, xStateOutput9, xStateOutput10, xStateOutput11, xStateOutput12, xStateOutput13, xStateOutput14, xStateOutput15, xStateOutput16, xStateOutput17, xStateOutput18, xStateOutput19, xStateOutput20, xStateOutput21, xStateOutput22, xStateOutput23, xStateOutput24, xStateOutput25, xStateOutput26, xStateOutput27, xStateOutput28, xStateOutput29, xStateOutput30, xStateOutput31, xStateOutput32, xStateOutput33, xStateOutput34, xStateOutput35, xStateOutput36, xStateOutput37, xStateOutput38, xStateOutput39, xStateOutput40, xStateOutput41, xStateOutput42, xStateOutput43, xStateOutput44, xStateOutput45, xStateOutput46, xStateOutput47, xStateOutput48: BOOL;
xCommandOutput1, xCommandOutput2, xCommandOutput3, xCommandOutput4, xCommandOutput5, xCommandOutput6, xCommandOutput7, xCommandOutput8, xCommandOutput9: BOOL;

END_VAR
VAR
	inst0Rtu117SJ6xmeasure0 : Rtu117SJ6xmeasure0;
inst0Rtu487SJ6xstate0 : Rtu487SJ6xstate0;
inst0Rtu97SJ6xcommand0 : Rtu97SJ6xcommand0;

END_VAR
(* @END_DECLARATION := '0' *)
_FBD_BODY
_NETWORKS : 3
_NETWORK
_COMMENT
''
_END_COMMENT
_ASSIGN
_FUNCTIONBLOCK
inst0Rtu117SJ6xmeasure0
_BOX_EXPR : 38
_OPERAND
_EXPRESSION
_POSITIV
xFirstCycle
_OPERAND
_EXPRESSION
_POSITIV
iSequenceOrder
_OPERAND
_EXPRESSION
_POSITIV
sProtocol
_OPERAND
_EXPRESSION
_POSITIV
eState
_OPERAND
_EXPRESSION
_POSITIV
MONITOR
_OPERAND
_EXPRESSION
_POSITIV
wMeasure1
_OPERAND
_EXPRESSION
_POSITIV
wMeasure2
_OPERAND
_EXPRESSION
_POSITIV
wMeasure3
_OPERAND
_EXPRESSION
_POSITIV
wMeasure4
_OPERAND
_EXPRESSION
_POSITIV
wMeasure5
_OPERAND
_EXPRESSION
_POSITIV
wMeasure6
_OPERAND
_EXPRESSION
_POSITIV
wMeasure7
_OPERAND
_EXPRESSION
_POSITIV
wMeasure8
_OPERAND
_EXPRESSION
_POSITIV
wMeasure9
_OPERAND
_EXPRESSION
_POSITIV
wMeasure10
_OPERAND
_EXPRESSION
_POSITIV
wMeasure11
_OPERAND
_EXPRESSION
_POSITIV
xSaveMeasure1
_OPERAND
_EXPRESSION
_POSITIV
xSaveMeasure2
_OPERAND
_EXPRESSION
_POSITIV
xSaveMeasure3
_OPERAND
_EXPRESSION
_POSITIV
xSaveMeasure4
_OPERAND
_EXPRESSION
_POSITIV
xSaveMeasure5
_OPERAND
_EXPRESSION
_POSITIV
xSaveMeasure6
_OPERAND
_EXPRESSION
_POSITIV
xSaveMeasure7
_OPERAND
_EXPRESSION
_POSITIV
xSaveMeasure8
_OPERAND
_EXPRESSION
_POSITIV
xSaveMeasure9
_OPERAND
_EXPRESSION
_POSITIV
xSaveMeasure10
_OPERAND
_EXPRESSION
_POSITIV
xSaveMeasure11
_OPERAND
_EXPRESSION
_POSITIV
sNameMeasure1
_OPERAND
_EXPRESSION
_POSITIV
sNameMeasure2
_OPERAND
_EXPRESSION
_POSITIV
sNameMeasure3
_OPERAND
_EXPRESSION
_POSITIV
sNameMeasure4
_OPERAND
_EXPRESSION
_POSITIV
sNameMeasure5
_OPERAND
_EXPRESSION
_POSITIV
sNameMeasure6
_OPERAND
_EXPRESSION
_POSITIV
sNameMeasure7
_OPERAND
_EXPRESSION
_POSITIV
sNameMeasure8
_OPERAND
_EXPRESSION
_POSITIV
sNameMeasure9
_OPERAND
_EXPRESSION
_POSITIV
sNameMeasure10
_OPERAND
_EXPRESSION
_POSITIV
sNameMeasure11
_EXPRESSION
_POSITIV
Rtu117SJ6xmeasure0
_OUTPUTS : 10
_OUTPUT
_POSITIV
_NO_SET
wMeasureOutput2
_OUTPUT
_POSITIV
_NO_SET
wMeasureOutput3
_OUTPUT
_POSITIV
_NO_SET
wMeasureOutput4
_OUTPUT
_POSITIV
_NO_SET
wMeasureOutput5
_OUTPUT
_POSITIV
_NO_SET
wMeasureOutput6
_OUTPUT
_POSITIV
_NO_SET
wMeasureOutput7
_OUTPUT
_POSITIV
_NO_SET
wMeasureOutput8
_OUTPUT
_POSITIV
_NO_SET
wMeasureOutput9
_OUTPUT
_POSITIV
_NO_SET
wMeasureOutput10
_OUTPUT
_POSITIV
_NO_SET
wMeasureOutput11
_EXPRESSION
_POSITIV

_OUTPUTS : 1
_OUTPUT
_POSITIV
_NO_SET
wMeasureOutput1
_NETWORK
_COMMENT
''
_END_COMMENT
_ASSIGN
_FUNCTIONBLOCK
inst0Rtu487SJ6xstate0
_BOX_EXPR : 197
_OPERAND
_EXPRESSION
_POSITIV
xFirstCycle
_OPERAND
_EXPRESSION
_POSITIV
iSequenceOrder
_OPERAND
_EXPRESSION
_POSITIV
sProtocol
_OPERAND
_EXPRESSION
_POSITIV
eState
_OPERAND
_EXPRESSION
_POSITIV
MONITOR
_OPERAND
_EXPRESSION
_POSITIV
xState1
_OPERAND
_EXPRESSION
_POSITIV
xState2
_OPERAND
_EXPRESSION
_POSITIV
xState3
_OPERAND
_EXPRESSION
_POSITIV
xState4
_OPERAND
_EXPRESSION
_POSITIV
xState5
_OPERAND
_EXPRESSION
_POSITIV
xState6
_OPERAND
_EXPRESSION
_POSITIV
xState7
_OPERAND
_EXPRESSION
_POSITIV
xState8
_OPERAND
_EXPRESSION
_POSITIV
xState9
_OPERAND
_EXPRESSION
_POSITIV
xState10
_OPERAND
_EXPRESSION
_POSITIV
xState11
_OPERAND
_EXPRESSION
_POSITIV
xState12
_OPERAND
_EXPRESSION
_POSITIV
xState13
_OPERAND
_EXPRESSION
_POSITIV
xState14
_OPERAND
_EXPRESSION
_POSITIV
xState15
_OPERAND
_EXPRESSION
_POSITIV
xState16
_OPERAND
_EXPRESSION
_POSITIV
xState17
_OPERAND
_EXPRESSION
_POSITIV
xState18
_OPERAND
_EXPRESSION
_POSITIV
xState19
_OPERAND
_EXPRESSION
_POSITIV
xState20
_OPERAND
_EXPRESSION
_POSITIV
xState21
_OPERAND
_EXPRESSION
_POSITIV
xState22
_OPERAND
_EXPRESSION
_POSITIV
xState23
_OPERAND
_EXPRESSION
_POSITIV
xState24
_OPERAND
_EXPRESSION
_POSITIV
xState25
_OPERAND
_EXPRESSION
_POSITIV
xState26
_OPERAND
_EXPRESSION
_POSITIV
xState27
_OPERAND
_EXPRESSION
_POSITIV
xState28
_OPERAND
_EXPRESSION
_POSITIV
xState29
_OPERAND
_EXPRESSION
_POSITIV
xState30
_OPERAND
_EXPRESSION
_POSITIV
xState31
_OPERAND
_EXPRESSION
_POSITIV
xState32
_OPERAND
_EXPRESSION
_POSITIV
xState33
_OPERAND
_EXPRESSION
_POSITIV
xState34
_OPERAND
_EXPRESSION
_POSITIV
xState35
_OPERAND
_EXPRESSION
_POSITIV
xState36
_OPERAND
_EXPRESSION
_POSITIV
xState37
_OPERAND
_EXPRESSION
_POSITIV
xState38
_OPERAND
_EXPRESSION
_POSITIV
xState39
_OPERAND
_EXPRESSION
_POSITIV
xState40
_OPERAND
_EXPRESSION
_POSITIV
xState41
_OPERAND
_EXPRESSION
_POSITIV
xState42
_OPERAND
_EXPRESSION
_POSITIV
xState43
_OPERAND
_EXPRESSION
_POSITIV
xState44
_OPERAND
_EXPRESSION
_POSITIV
xState45
_OPERAND
_EXPRESSION
_POSITIV
xState46
_OPERAND
_EXPRESSION
_POSITIV
xState47
_OPERAND
_EXPRESSION
_POSITIV
xState48
_OPERAND
_EXPRESSION
_POSITIV
xSaveState1
_OPERAND
_EXPRESSION
_POSITIV
xSaveState2
_OPERAND
_EXPRESSION
_POSITIV
xSaveState3
_OPERAND
_EXPRESSION
_POSITIV
xSaveState4
_OPERAND
_EXPRESSION
_POSITIV
xSaveState5
_OPERAND
_EXPRESSION
_POSITIV
xSaveState6
_OPERAND
_EXPRESSION
_POSITIV
xSaveState7
_OPERAND
_EXPRESSION
_POSITIV
xSaveState8
_OPERAND
_EXPRESSION
_POSITIV
xSaveState9
_OPERAND
_EXPRESSION
_POSITIV
xSaveState10
_OPERAND
_EXPRESSION
_POSITIV
xSaveState11
_OPERAND
_EXPRESSION
_POSITIV
xSaveState12
_OPERAND
_EXPRESSION
_POSITIV
xSaveState13
_OPERAND
_EXPRESSION
_POSITIV
xSaveState14
_OPERAND
_EXPRESSION
_POSITIV
xSaveState15
_OPERAND
_EXPRESSION
_POSITIV
xSaveState16
_OPERAND
_EXPRESSION
_POSITIV
xSaveState17
_OPERAND
_EXPRESSION
_POSITIV
xSaveState18
_OPERAND
_EXPRESSION
_POSITIV
xSaveState19
_OPERAND
_EXPRESSION
_POSITIV
xSaveState20
_OPERAND
_EXPRESSION
_POSITIV
xSaveState21
_OPERAND
_EXPRESSION
_POSITIV
xSaveState22
_OPERAND
_EXPRESSION
_POSITIV
xSaveState23
_OPERAND
_EXPRESSION
_POSITIV
xSaveState24
_OPERAND
_EXPRESSION
_POSITIV
xSaveState25
_OPERAND
_EXPRESSION
_POSITIV
xSaveState26
_OPERAND
_EXPRESSION
_POSITIV
xSaveState27
_OPERAND
_EXPRESSION
_POSITIV
xSaveState28
_OPERAND
_EXPRESSION
_POSITIV
xSaveState29
_OPERAND
_EXPRESSION
_POSITIV
xSaveState30
_OPERAND
_EXPRESSION
_POSITIV
xSaveState31
_OPERAND
_EXPRESSION
_POSITIV
xSaveState32
_OPERAND
_EXPRESSION
_POSITIV
xSaveState33
_OPERAND
_EXPRESSION
_POSITIV
xSaveState34
_OPERAND
_EXPRESSION
_POSITIV
xSaveState35
_OPERAND
_EXPRESSION
_POSITIV
xSaveState36
_OPERAND
_EXPRESSION
_POSITIV
xSaveState37
_OPERAND
_EXPRESSION
_POSITIV
xSaveState38
_OPERAND
_EXPRESSION
_POSITIV
xSaveState39
_OPERAND
_EXPRESSION
_POSITIV
xSaveState40
_OPERAND
_EXPRESSION
_POSITIV
xSaveState41
_OPERAND
_EXPRESSION
_POSITIV
xSaveState42
_OPERAND
_EXPRESSION
_POSITIV
xSaveState43
_OPERAND
_EXPRESSION
_POSITIV
xSaveState44
_OPERAND
_EXPRESSION
_POSITIV
xSaveState45
_OPERAND
_EXPRESSION
_POSITIV
xSaveState46
_OPERAND
_EXPRESSION
_POSITIV
xSaveState47
_OPERAND
_EXPRESSION
_POSITIV
xSaveState48
_OPERAND
_EXPRESSION
_POSITIV
sNameState1
_OPERAND
_EXPRESSION
_POSITIV
sNameState2
_OPERAND
_EXPRESSION
_POSITIV
sNameState3
_OPERAND
_EXPRESSION
_POSITIV
sNameState4
_OPERAND
_EXPRESSION
_POSITIV
sNameState5
_OPERAND
_EXPRESSION
_POSITIV
sNameState6
_OPERAND
_EXPRESSION
_POSITIV
sNameState7
_OPERAND
_EXPRESSION
_POSITIV
sNameState8
_OPERAND
_EXPRESSION
_POSITIV
sNameState9
_OPERAND
_EXPRESSION
_POSITIV
sNameState10
_OPERAND
_EXPRESSION
_POSITIV
sNameState11
_OPERAND
_EXPRESSION
_POSITIV
sNameState12
_OPERAND
_EXPRESSION
_POSITIV
sNameState13
_OPERAND
_EXPRESSION
_POSITIV
sNameState14
_OPERAND
_EXPRESSION
_POSITIV
sNameState15
_OPERAND
_EXPRESSION
_POSITIV
sNameState16
_OPERAND
_EXPRESSION
_POSITIV
sNameState17
_OPERAND
_EXPRESSION
_POSITIV
sNameState18
_OPERAND
_EXPRESSION
_POSITIV
sNameState19
_OPERAND
_EXPRESSION
_POSITIV
sNameState20
_OPERAND
_EXPRESSION
_POSITIV
sNameState21
_OPERAND
_EXPRESSION
_POSITIV
sNameState22
_OPERAND
_EXPRESSION
_POSITIV
sNameState23
_OPERAND
_EXPRESSION
_POSITIV
sNameState24
_OPERAND
_EXPRESSION
_POSITIV
sNameState25
_OPERAND
_EXPRESSION
_POSITIV
sNameState26
_OPERAND
_EXPRESSION
_POSITIV
sNameState27
_OPERAND
_EXPRESSION
_POSITIV
sNameState28
_OPERAND
_EXPRESSION
_POSITIV
sNameState29
_OPERAND
_EXPRESSION
_POSITIV
sNameState30
_OPERAND
_EXPRESSION
_POSITIV
sNameState31
_OPERAND
_EXPRESSION
_POSITIV
sNameState32
_OPERAND
_EXPRESSION
_POSITIV
sNameState33
_OPERAND
_EXPRESSION
_POSITIV
sNameState34
_OPERAND
_EXPRESSION
_POSITIV
sNameState35
_OPERAND
_EXPRESSION
_POSITIV
sNameState36
_OPERAND
_EXPRESSION
_POSITIV
sNameState37
_OPERAND
_EXPRESSION
_POSITIV
sNameState38
_OPERAND
_EXPRESSION
_POSITIV
sNameState39
_OPERAND
_EXPRESSION
_POSITIV
sNameState40
_OPERAND
_EXPRESSION
_POSITIV
sNameState41
_OPERAND
_EXPRESSION
_POSITIV
sNameState42
_OPERAND
_EXPRESSION
_POSITIV
sNameState43
_OPERAND
_EXPRESSION
_POSITIV
sNameState44
_OPERAND
_EXPRESSION
_POSITIV
sNameState45
_OPERAND
_EXPRESSION
_POSITIV
sNameState46
_OPERAND
_EXPRESSION
_POSITIV
sNameState47
_OPERAND
_EXPRESSION
_POSITIV
sNameState48
_OPERAND
_EXPRESSION
_POSITIV
byRiseState1
_OPERAND
_EXPRESSION
_POSITIV
byRiseState2
_OPERAND
_EXPRESSION
_POSITIV
byRiseState3
_OPERAND
_EXPRESSION
_POSITIV
byRiseState4
_OPERAND
_EXPRESSION
_POSITIV
byRiseState5
_OPERAND
_EXPRESSION
_POSITIV
byRiseState6
_OPERAND
_EXPRESSION
_POSITIV
byRiseState7
_OPERAND
_EXPRESSION
_POSITIV
byRiseState8
_OPERAND
_EXPRESSION
_POSITIV
byRiseState9
_OPERAND
_EXPRESSION
_POSITIV
byRiseState10
_OPERAND
_EXPRESSION
_POSITIV
byRiseState11
_OPERAND
_EXPRESSION
_POSITIV
byRiseState12
_OPERAND
_EXPRESSION
_POSITIV
byRiseState13
_OPERAND
_EXPRESSION
_POSITIV
byRiseState14
_OPERAND
_EXPRESSION
_POSITIV
byRiseState15
_OPERAND
_EXPRESSION
_POSITIV
byRiseState16
_OPERAND
_EXPRESSION
_POSITIV
byRiseState17
_OPERAND
_EXPRESSION
_POSITIV
byRiseState18
_OPERAND
_EXPRESSION
_POSITIV
byRiseState19
_OPERAND
_EXPRESSION
_POSITIV
byRiseState20
_OPERAND
_EXPRESSION
_POSITIV
byRiseState21
_OPERAND
_EXPRESSION
_POSITIV
byRiseState22
_OPERAND
_EXPRESSION
_POSITIV
byRiseState23
_OPERAND
_EXPRESSION
_POSITIV
byRiseState24
_OPERAND
_EXPRESSION
_POSITIV
byRiseState25
_OPERAND
_EXPRESSION
_POSITIV
byRiseState26
_OPERAND
_EXPRESSION
_POSITIV
byRiseState27
_OPERAND
_EXPRESSION
_POSITIV
byRiseState28
_OPERAND
_EXPRESSION
_POSITIV
byRiseState29
_OPERAND
_EXPRESSION
_POSITIV
byRiseState30
_OPERAND
_EXPRESSION
_POSITIV
byRiseState31
_OPERAND
_EXPRESSION
_POSITIV
byRiseState32
_OPERAND
_EXPRESSION
_POSITIV
byRiseState33
_OPERAND
_EXPRESSION
_POSITIV
byRiseState34
_OPERAND
_EXPRESSION
_POSITIV
byRiseState35
_OPERAND
_EXPRESSION
_POSITIV
byRiseState36
_OPERAND
_EXPRESSION
_POSITIV
byRiseState37
_OPERAND
_EXPRESSION
_POSITIV
byRiseState38
_OPERAND
_EXPRESSION
_POSITIV
byRiseState39
_OPERAND
_EXPRESSION
_POSITIV
byRiseState40
_OPERAND
_EXPRESSION
_POSITIV
byRiseState41
_OPERAND
_EXPRESSION
_POSITIV
byRiseState42
_OPERAND
_EXPRESSION
_POSITIV
byRiseState43
_OPERAND
_EXPRESSION
_POSITIV
byRiseState44
_OPERAND
_EXPRESSION
_POSITIV
byRiseState45
_OPERAND
_EXPRESSION
_POSITIV
byRiseState46
_OPERAND
_EXPRESSION
_POSITIV
byRiseState47
_OPERAND
_EXPRESSION
_POSITIV
byRiseState48
_EXPRESSION
_POSITIV
Rtu487SJ6xstate0
_OUTPUTS : 47
_OUTPUT
_POSITIV
_NO_SET
xStateOutput2
_OUTPUT
_POSITIV
_NO_SET
xStateOutput3
_OUTPUT
_POSITIV
_NO_SET
xStateOutput4
_OUTPUT
_POSITIV
_NO_SET
xStateOutput5
_OUTPUT
_POSITIV
_NO_SET
xStateOutput6
_OUTPUT
_POSITIV
_NO_SET
xStateOutput7
_OUTPUT
_POSITIV
_NO_SET
xStateOutput8
_OUTPUT
_POSITIV
_NO_SET
xStateOutput9
_OUTPUT
_POSITIV
_NO_SET
xStateOutput10
_OUTPUT
_POSITIV
_NO_SET
xStateOutput11
_OUTPUT
_POSITIV
_NO_SET
xStateOutput12
_OUTPUT
_POSITIV
_NO_SET
xStateOutput13
_OUTPUT
_POSITIV
_NO_SET
xStateOutput14
_OUTPUT
_POSITIV
_NO_SET
xStateOutput15
_OUTPUT
_POSITIV
_NO_SET
xStateOutput16
_OUTPUT
_POSITIV
_NO_SET
xStateOutput17
_OUTPUT
_POSITIV
_NO_SET
xStateOutput18
_OUTPUT
_POSITIV
_NO_SET
xStateOutput19
_OUTPUT
_POSITIV
_NO_SET
xStateOutput20
_OUTPUT
_POSITIV
_NO_SET
xStateOutput21
_OUTPUT
_POSITIV
_NO_SET
xStateOutput22
_OUTPUT
_POSITIV
_NO_SET
xStateOutput23
_OUTPUT
_POSITIV
_NO_SET
xStateOutput24
_OUTPUT
_POSITIV
_NO_SET
xStateOutput25
_OUTPUT
_POSITIV
_NO_SET
xStateOutput26
_OUTPUT
_POSITIV
_NO_SET
xStateOutput27
_OUTPUT
_POSITIV
_NO_SET
xStateOutput28
_OUTPUT
_POSITIV
_NO_SET
xStateOutput29
_OUTPUT
_POSITIV
_NO_SET
xStateOutput30
_OUTPUT
_POSITIV
_NO_SET
xStateOutput31
_OUTPUT
_POSITIV
_NO_SET
xStateOutput32
_OUTPUT
_POSITIV
_NO_SET
xStateOutput33
_OUTPUT
_POSITIV
_NO_SET
xStateOutput34
_OUTPUT
_POSITIV
_NO_SET
xStateOutput35
_OUTPUT
_POSITIV
_NO_SET
xStateOutput36
_OUTPUT
_POSITIV
_NO_SET
xStateOutput37
_OUTPUT
_POSITIV
_NO_SET
xStateOutput38
_OUTPUT
_POSITIV
_NO_SET
xStateOutput39
_OUTPUT
_POSITIV
_NO_SET
xStateOutput40
_OUTPUT
_POSITIV
_NO_SET
xStateOutput41
_OUTPUT
_POSITIV
_NO_SET
xStateOutput42
_OUTPUT
_POSITIV
_NO_SET
xStateOutput43
_OUTPUT
_POSITIV
_NO_SET
xStateOutput44
_OUTPUT
_POSITIV
_NO_SET
xStateOutput45
_OUTPUT
_POSITIV
_NO_SET
xStateOutput46
_OUTPUT
_POSITIV
_NO_SET
xStateOutput47
_OUTPUT
_POSITIV
_NO_SET
xStateOutput48
_EXPRESSION
_POSITIV

_OUTPUTS : 1
_OUTPUT
_POSITIV
_NO_SET
xStateOutput1
_NETWORK
_COMMENT
''
_END_COMMENT
_ASSIGN
_FUNCTIONBLOCK
inst0Rtu97SJ6xcommand0
_BOX_EXPR : 41
_OPERAND
_EXPRESSION
_POSITIV
xFirstCycle
_OPERAND
_EXPRESSION
_POSITIV
iSequenceOrder
_OPERAND
_EXPRESSION
_POSITIV
sProtocol
_OPERAND
_EXPRESSION
_POSITIV
eState
_OPERAND
_EXPRESSION
_POSITIV
CONTROL
_OPERAND
_EXPRESSION
_POSITIV
xCommand1
_OPERAND
_EXPRESSION
_POSITIV
xCommand2
_OPERAND
_EXPRESSION
_POSITIV
xCommand3
_OPERAND
_EXPRESSION
_POSITIV
xCommand4
_OPERAND
_EXPRESSION
_POSITIV
xCommand5
_OPERAND
_EXPRESSION
_POSITIV
xCommand6
_OPERAND
_EXPRESSION
_POSITIV
xCommand7
_OPERAND
_EXPRESSION
_POSITIV
xCommand8
_OPERAND
_EXPRESSION
_POSITIV
xCommand9
_OPERAND
_EXPRESSION
_POSITIV
xSaveCommand1
_OPERAND
_EXPRESSION
_POSITIV
xSaveCommand2
_OPERAND
_EXPRESSION
_POSITIV
xSaveCommand3
_OPERAND
_EXPRESSION
_POSITIV
xSaveCommand4
_OPERAND
_EXPRESSION
_POSITIV
xSaveCommand5
_OPERAND
_EXPRESSION
_POSITIV
xSaveCommand6
_OPERAND
_EXPRESSION
_POSITIV
xSaveCommand7
_OPERAND
_EXPRESSION
_POSITIV
xSaveCommand8
_OPERAND
_EXPRESSION
_POSITIV
xSaveCommand9
_OPERAND
_EXPRESSION
_POSITIV
sNameCommand1
_OPERAND
_EXPRESSION
_POSITIV
sNameCommand2
_OPERAND
_EXPRESSION
_POSITIV
sNameCommand3
_OPERAND
_EXPRESSION
_POSITIV
sNameCommand4
_OPERAND
_EXPRESSION
_POSITIV
sNameCommand5
_OPERAND
_EXPRESSION
_POSITIV
sNameCommand6
_OPERAND
_EXPRESSION
_POSITIV
sNameCommand7
_OPERAND
_EXPRESSION
_POSITIV
sNameCommand8
_OPERAND
_EXPRESSION
_POSITIV
sNameCommand9
_OPERAND
_EXPRESSION
_POSITIV
xTriggerCommand1
_OPERAND
_EXPRESSION
_POSITIV
xTriggerCommand2
_OPERAND
_EXPRESSION
_POSITIV
xTriggerCommand3
_OPERAND
_EXPRESSION
_POSITIV
xTriggerCommand4
_OPERAND
_EXPRESSION
_POSITIV
xTriggerCommand5
_OPERAND
_EXPRESSION
_POSITIV
xTriggerCommand6
_OPERAND
_EXPRESSION
_POSITIV
xTriggerCommand7
_OPERAND
_EXPRESSION
_POSITIV
xTriggerCommand8
_OPERAND
_EXPRESSION
_POSITIV
xTriggerCommand9
_EXPRESSION
_POSITIV
Rtu97SJ6xcommand0
_OUTPUTS : 8
_OUTPUT
_POSITIV
_NO_SET
xCommandOutput2
_OUTPUT
_POSITIV
_NO_SET
xCommandOutput3
_OUTPUT
_POSITIV
_NO_SET
xCommandOutput4
_OUTPUT
_POSITIV
_NO_SET
xCommandOutput5
_OUTPUT
_POSITIV
_NO_SET
xCommandOutput6
_OUTPUT
_POSITIV
_NO_SET
xCommandOutput7
_OUTPUT
_POSITIV
_NO_SET
xCommandOutput8
_OUTPUT
_POSITIV
_NO_SET
xCommandOutput9
_EXPRESSION
_POSITIV

_OUTPUTS : 1
_OUTPUT
_POSITIV
_NO_SET
xCommandOutput1
END_FUNCTION_BLOCK
