# Generated by Django 2.1.5 on 2019-10-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
