# Generated by Django 2.1.5 on 2019-10-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0003_auto_20191017_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='protocol',
            field=models.TextField(default='NONE'),
        ),
    ]
