# Generated by Django 2.1.5 on 2019-10-24 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0004_device_protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='protocol',
        ),
    ]
