# Generated by Django 2.1.5 on 2019-10-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0005_remove_device_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.TextField(default='NONE'),
        ),
    ]
