# Generated by Django 2.1.5 on 2019-11-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0006_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='client',
            field=models.TextField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=2),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('103', '103'), ('104', '104')], default='103', max_length=2),
        ),
    ]
