# Generated by Django 2.1.5 on 2019-11-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0007_auto_20191108_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='client',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=2),
        ),
    ]
