# Generated by Django 2.1.5 on 2019-11-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0008_auto_20191108_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('103', '103'), ('104', '104')], default='103', max_length=3),
        ),
    ]
