# Generated by Django 2.1.5 on 2019-11-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0010_auto_20191108_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='server',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3),
        ),
    ]
