# Generated by Django 2.1.5 on 2019-12-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0011_device_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3)),
                ('Name', models.CharField(default='7SJ6x', max_length=255)),
                ('MonitorIoa', models.IntegerField(default=1000)),
                ('MonitorIoaJump', models.IntegerField(default=100)),
                ('MonitorObjectList', models.TextField(default='')),
                ('ControlIoa', models.IntegerField(default=1000)),
                ('ControlIoaJump', models.IntegerField(default=100)),
                ('ControlObjectList', models.TextField(default='')),
                ('Client', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
