# Generated by Django 2.1.5 on 2019-12-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0012_auto_20191201_1951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Device',
        ),
    ]
