# Generated by Django 2.1.5 on 2019-12-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0013_auto_20191201_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='Control',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='device',
            name='Monitor',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3),
        ),
    ]
