# Generated by Django 2.1.5 on 2019-12-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0015_auto_20191202_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Client',
            field=models.TextField(default=''),
        ),
    ]
