# Generated by Django 2.1.5 on 2019-12-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0016_auto_20191204_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Client',
            field=models.TextField(blank=True),
        ),
    ]
