# Generated by Django 2.1.5 on 2019-12-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0018_auto_20191204_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ControlObjectList',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='MonitorObjectList',
            field=models.TextField(blank=True),
        ),
    ]
