# Generated by Django 2.1.5 on 2019-12-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0020_auto_20191205_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='Client',
        ),
    ]
