# Generated by Django 2.1.5 on 2019-12-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0022_auto_20191205_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ControlObjectList',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='MonitorObjectList',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
