# Generated by Django 2.1.5 on 2019-12-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0023_auto_20191205_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Protocol',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
