# Generated by Django 2.1.5 on 2019-12-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0024_auto_20191212_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='OperationMode',
            field=models.CharField(choices=[('DO', 'DO'), ('SBO', 'SBO')], default='DO', max_length=255),
        ),
    ]
