# Generated by Django 2.1.5 on 2019-12-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0025_device_operationmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Protocol',
            field=models.CharField(choices=[('MODBUS', 'MODBUS'), ('103', '103'), ('104', '104')], default='104', max_length=255),
        ),
    ]
