# Generated by Django 2.1.5 on 2019-12-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0026_auto_20191219_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='OperationMode',
            field=models.BooleanField(default=False),
        ),
    ]
