# Generated by Django 2.1.5 on 2019-12-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0027_auto_20191226_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='OperationMode',
        ),
        migrations.AddField(
            model_name='device',
            name='DO',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='SBO',
            field=models.BooleanField(default=False),
        ),
    ]
