# Generated by Django 2.1.5 on 2019-12-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0028_auto_20191226_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='Server',
        ),
    ]
