# Generated by Django 2.1.5 on 2019-12-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0029_remove_device_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='Server',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=255),
        ),
    ]
