# Generated by Django 2.1.5 on 2020-01-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0030_device_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='Server',
        ),
    ]
