# Generated by Django 2.1.5 on 2020-02-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0034_auto_20200206_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Protocol',
            field=models.CharField(choices=[('MODBUS_TCP', 'MODBUS_TCP'), ('IEC_103', 'IEC_103'), ('IEC_104', 'IEC_104')], default='104', max_length=255),
        ),
    ]
