# Generated by Django 2.1.5 on 2020-02-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0035_auto_20200208_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='ClientObjs',
        ),
        migrations.RemoveField(
            model_name='device',
            name='ClientSignals',
        ),
    ]
