# Generated by Django 2.1.5 on 2019-11-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='7SJ6x')),
                ('ioa', models.TextField(default='ioa')),
                ('object_list', models.TextField()),
            ],
        ),
    ]
