# Generated by Django 2.1.5 on 2019-11-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obj35mMeTe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.TextField()),
                ('hysteresis', models.TextField()),
                ('SVA', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='ioa',
        ),
    ]
