# Generated by Django 2.1.5 on 2019-11-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0003_auto_20191201_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='obj35mmete',
            name='ObjInfo',
            field=models.TextField(default='None'),
        ),
    ]
