# Generated by Django 2.1.5 on 2019-11-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0004_obj35mmete_objinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obj31mDpTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceName', models.TextField()),
                ('DPI0', models.TextField()),
                ('DPI1', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObjCode', models.TextField()),
                ('ObjInfo', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='obj35mmete',
            old_name='device_name',
            new_name='DeviceName',
        ),
        migrations.RenameField(
            model_name='obj35mmete',
            old_name='hysteresis',
            new_name='Hysteresis',
        ),
        migrations.RemoveField(
            model_name='obj35mmete',
            name='ObjInfo',
        ),
    ]
