# Generated by Django 2.1.5 on 2019-11-30 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0005_auto_20191201_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obj31mdptb',
            old_name='DPI0',
            new_name='DPI',
        ),
        migrations.RemoveField(
            model_name='obj31mdptb',
            name='DPI1',
        ),
    ]
