# Generated by Django 2.1.5 on 2019-11-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0006_auto_20191201_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obj58cScTa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceName', models.TextField()),
                ('SCS', models.TextField()),
            ],
        ),
    ]
