# Generated by Django 2.1.5 on 2019-12-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0007_obj58cscta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='object_list',
            new_name='ObjectList',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='header',
            new_name='Header',
        ),
        migrations.AddField(
            model_name='item',
            name='IoaControl',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='IoaMonitor',
            field=models.TextField(default=''),
        ),
    ]
