# Generated by Django 2.1.5 on 2019-12-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0009_auto_20191201_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ObjectList',
            field=models.TextField(default=''),
        ),
    ]
