# Generated by Django 2.1.5 on 2019-12-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0010_auto_20191201_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='IoaControl',
        ),
        migrations.RemoveField(
            model_name='item',
            name='IoaMonitor',
        ),
    ]
