# Generated by Django 2.1.5 on 2019-12-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0011_auto_20191201_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='IoaControl',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='IoaMonitor',
            field=models.IntegerField(default=1000),
        ),
    ]
