# Generated by Django 2.1.5 on 2019-12-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0012_auto_20191201_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='7SJ6x', max_length=255),
        ),
    ]
