# Generated by Django 2.1.5 on 2019-12-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0013_auto_20191201_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ObjectList',
            new_name='ControlObjectList',
        ),
        migrations.AddField(
            model_name='item',
            name='IoaControlJump',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='item',
            name='IoaMonitorJump',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='item',
            name='MonitorObjectList',
            field=models.TextField(default=''),
        ),
    ]
