# Generated by Django 2.1.5 on 2019-12-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0014_auto_20191201_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='closingTag',
            field=models.TextField(default='closing tag'),
        ),
    ]
