# Generated by Django 2.1.5 on 2019-12-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0015_server_closingtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='closingTag',
            new_name='ClosingTag',
        ),
    ]
