# Generated by Django 2.1.5 on 2019-12-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0016_auto_20191201_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='IoaControl',
            new_name='ControlIoa',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='IoaControlJump',
            new_name='ControlIoaJump',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='IoaMonitor',
            new_name='MonitorIoa',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='IoaMonitorJump',
            new_name='MonitorIoaJump',
        ),
    ]
