# Generated by Django 2.1.5 on 2019-12-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0018_auto_20191201_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obj30mSpTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceName', models.CharField(max_length=255)),
                ('SPI', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='obj31mdptb',
            name='DeviceName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='obj35mmete',
            name='DeviceName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='obj58cscta',
            name='DeviceName',
            field=models.CharField(max_length=255),
        ),
    ]
