# Generated by Django 2.1.5 on 2019-12-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0020_auto_20191201_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Client',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='item',
            name='Server',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3),
        ),
    ]
