# Generated by Django 2.1.5 on 2019-12-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0021_auto_20191201_1933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
