# Generated by Django 2.1.5 on 2019-12-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0022_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obj09mMeiiNa3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceName', models.CharField(max_length=255)),
                ('MEA', models.TextField()),
            ],
        ),
    ]
