# Generated by Django 2.1.5 on 2019-12-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0023_obj09mmeiina3'),
    ]

    operations = [
        migrations.AddField(
            model_name='obj09mmeiina3',
            name='DataType',
            field=models.CharField(choices=[('BOOL', 'BOOL'), ('WORD', 'WORD')], default='BOOL', max_length=255),
        ),
        migrations.AddField(
            model_name='obj30msptb',
            name='DataType',
            field=models.CharField(choices=[('BOOL', 'BOOL'), ('WORD', 'WORD')], default='BOOL', max_length=255),
        ),
        migrations.AddField(
            model_name='obj31mdptb',
            name='DataType',
            field=models.CharField(choices=[('BOOL', 'BOOL'), ('WORD', 'WORD')], default='BOOL', max_length=255),
        ),
        migrations.AddField(
            model_name='obj35mmete',
            name='DataType',
            field=models.CharField(choices=[('BOOL', 'BOOL'), ('WORD', 'WORD')], default='BOOL', max_length=255),
        ),
        migrations.AddField(
            model_name='obj58cscta',
            name='DataType',
            field=models.CharField(choices=[('BOOL', 'BOOL'), ('WORD', 'WORD')], default='BOOL', max_length=255),
        ),
    ]
