# Generated by Django 2.1.5 on 2019-12-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0024_auto_20191210_1013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Obj09mMeiiNa3',
        ),
    ]
