# Generated by Django 2.1.5 on 2020-01-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0026_obj59cdcta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obj30msptb',
            options={'verbose_name_plural': 'obj_30m_sp_tb'},
        ),
        migrations.AlterModelOptions(
            name='obj31mdptb',
            options={'verbose_name_plural': 'obj_31m_dp_tb'},
        ),
        migrations.AlterModelOptions(
            name='obj35mmete',
            options={'verbose_name_plural': 'obj_35m_me_te'},
        ),
        migrations.AlterModelOptions(
            name='obj58cscta',
            options={'verbose_name_plural': 'obj_58c_sc_ta'},
        ),
        migrations.AlterModelOptions(
            name='obj59cdcta',
            options={'verbose_name_plural': 'obj_59c_dc_ta'},
        ),
        migrations.AlterModelOptions(
            name='objsinfo',
            options={'verbose_name_plural': 'objInfo'},
        ),
        migrations.AddField(
            model_name='objsinfo',
            name='ObjType',
            field=models.CharField(choices=[('MONITOR', 'MONITOR'), ('CONTROL', 'CONTROL')], default=1, max_length=255),
        ),
    ]
