# Generated by Django 2.1.5 on 2020-02-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_parts', '0028_auto_20200204_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obj30msptb',
            name='DataType',
        ),
        migrations.RemoveField(
            model_name='obj31mdptb',
            name='DataType',
        ),
        migrations.RemoveField(
            model_name='obj35mmete',
            name='DataType',
        ),
        migrations.RemoveField(
            model_name='obj58cscta',
            name='DataType',
        ),
        migrations.RemoveField(
            model_name='obj59cdcta',
            name='DataType',
        ),
    ]
