# Generated by Django 2.1.5 on 2019-12-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client103',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client', models.CharField(max_length=255)),
                ('Headers', models.TextField(default='')),
                ('ClosingTag', models.TextField(default='')),
            ],
        ),
    ]
