# Generated by Django 2.1.5 on 2019-12-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client103',
            new_name='Client',
        ),
    ]
