# Generated by Django 2.1.5 on 2019-12-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20191204_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ConnectionHeaders',
            field=models.TextField(default=''),
        ),
    ]
