# Generated by Django 2.1.5 on 2019-12-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_connectionheaders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Client',
            new_name='Protocol',
        ),
    ]
