# Generated by Django 2.1.5 on 2019-12-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20191204_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Protocol',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
