# Generated by Django 2.1.5 on 2019-12-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20191212_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Protocol',
            field=models.CharField(max_length=255),
        ),
    ]
