# Generated by Django 2.1.5 on 2020-01-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0005_save'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Version', models.CharField(max_length=255)),
                ('VariableDeclaration', models.TextField(default='')),
                ('Initialization', models.TextField(default='')),
                ('Core', models.TextField(default='')),
                ('FinalCheck', models.TextField(default='')),
            ],
        ),
    ]
