# Generated by Django 2.1.5 on 2020-01-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0006_sbo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sbo',
            old_name='Initialization',
            new_name='Body',
        ),
    ]
