# Generated by Django 2.1.5 on 2020-01-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0008_rotate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rtu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VariableDeclaration', models.TextField(default='')),
                ('InputUnit', models.TextField(default='')),
                ('OutputUnit', models.TextField(default='')),
            ],
        ),
    ]
