# Generated by Django 2.1.5 on 2020-01-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0010_rtu_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtu',
            name='Version',
            field=models.CharField(max_length=255),
        ),
    ]
