# Generated by Django 2.1.5 on 2020-01-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0011_auto_20200108_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtu',
            name='InputUnit',
        ),
        migrations.RemoveField(
            model_name='rtu',
            name='OutputUnit',
        ),
    ]
