# Generated by Django 2.1.5 on 2020-01-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0012_auto_20200108_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbdTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.TextField(default='')),
                ('InputUnit', models.TextField(default='')),
                ('OutputUnit', models.TextField(default='')),
            ],
        ),
    ]
