# Generated by Django 2.1.5 on 2020-01-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0013_fbdtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbdtemplate',
            old_name='Header',
            new_name='InputHeader',
        ),
        migrations.AddField(
            model_name='fbdtemplate',
            name='OutputHeader',
            field=models.TextField(default=''),
        ),
    ]
