# Generated by Django 2.1.5 on 2020-01-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0014_auto_20200108_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbdtemplate',
            name='Header',
            field=models.TextField(default=''),
        ),
    ]
