# Generated by Django 2.1.5 on 2020-01-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0015_fbdtemplate_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtu',
            name='SboVariables',
            field=models.TextField(default=''),
        ),
    ]
