# Generated by Django 2.1.5 on 2020-01-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0016_rtu_sbovariables'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbdtemplate',
            name='Jump',
            field=models.TextField(default=''),
        ),
    ]
