# Generated by Django 2.1.5 on 2020-01-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0017_fbdtemplate_jump'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Version', models.CharField(default='', max_length=255)),
                ('SequenceOrder', models.CharField(default='', max_length=255)),
                ('SequenceOrderDataType', models.CharField(default='', max_length=255)),
                ('Protocol', models.CharField(default='', max_length=255)),
                ('ProtocolDataType', models.CharField(default='', max_length=255)),
                ('StateLocRem', models.CharField(default='', max_length=255)),
                ('StateLocRemDataType', models.CharField(default='', max_length=255)),
                ('Measure', models.CharField(default='', max_length=255)),
                ('MeasureDataType', models.CharField(default='', max_length=255)),
                ('MeasureOutput', models.CharField(default='', max_length=255)),
                ('MeasureOutputDataType', models.CharField(default='', max_length=255)),
                ('SaveMeasure', models.CharField(default='', max_length=255)),
                ('SaveMeasureDataType', models.CharField(default='', max_length=255)),
                ('NameMeasure', models.CharField(default='', max_length=255)),
                ('NameMeasureDataType', models.CharField(default='', max_length=255)),
                ('State', models.CharField(default='', max_length=255)),
                ('StateDataType', models.CharField(default='', max_length=255)),
                ('StateOutput', models.CharField(default='', max_length=255)),
                ('StateOutputDataType', models.CharField(default='', max_length=255)),
                ('SaveState', models.CharField(default='', max_length=255)),
                ('SaveStateDataType', models.CharField(default='', max_length=255)),
                ('NameState', models.CharField(default='', max_length=255)),
                ('NameStateDataType', models.CharField(default='', max_length=255)),
                ('TriggerState', models.CharField(default='', max_length=255)),
                ('TriggerStateDataType', models.CharField(default='', max_length=255)),
                ('Command', models.CharField(default='', max_length=255)),
                ('CommandDataType', models.CharField(default='', max_length=255)),
                ('CommandOutput', models.CharField(default='', max_length=255)),
                ('CommandOutputDataType', models.CharField(default='', max_length=255)),
                ('SaveCommand', models.CharField(default='', max_length=255)),
                ('SaveCommandDataType', models.CharField(default='', max_length=255)),
                ('NameCommand', models.CharField(default='', max_length=255)),
                ('NameCommandDataType', models.CharField(default='', max_length=255)),
                ('TriggerCommand', models.CharField(default='', max_length=255)),
                ('TriggerCommandDataType', models.CharField(default='', max_length=255)),
                ('Status', models.CharField(default='', max_length=255)),
                ('StatusDataType', models.CharField(default='', max_length=255)),
                ('Select', models.CharField(default='', max_length=255)),
                ('SelectDataType', models.CharField(default='', max_length=255)),
                ('Execute', models.CharField(default='', max_length=255)),
                ('ExecuteDataType', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RiseToTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Version', models.CharField(max_length=255)),
                ('LastRise', models.CharField(default='', max_length=255)),
                ('LastRiseDataType', models.CharField(default='', max_length=255)),
                ('Iterator', models.CharField(default='', max_length=255)),
                ('IteratorDataType', models.CharField(default='', max_length=255)),
                ('ST', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='STTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeclarationAttributes', models.TextField(default='')),
                ('DeclarationFBHeader', models.CharField(default='', max_length=255)),
                ('DeclarationFHeader', models.CharField(default='', max_length=255)),
                ('DeclarationInput', models.TextField(default='')),
                ('DeclarationOutput', models.TextField(default='')),
                ('DeclarationInternal', models.TextField(default='')),
                ('DeclarationEndTag', models.CharField(default='', max_length=255)),
                ('CodeEndTag', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserPrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Version', models.CharField(max_length=255)),
                ('FirstCycle', models.CharField(default='', max_length=255)),
                ('FirstCycleDataType', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Pack',
        ),
        migrations.DeleteModel(
            name='Rotate',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='Code',
            new_name='ST',
        ),
        migrations.RenameField(
            model_name='save',
            old_name='Code',
            new_name='ST',
        ),
        migrations.RenameField(
            model_name='sbo',
            old_name='Body',
            new_name='STBody',
        ),
        migrations.RenameField(
            model_name='sbo',
            old_name='Core',
            new_name='STCore',
        ),
        migrations.RemoveField(
            model_name='check',
            name='Code',
        ),
        migrations.RemoveField(
            model_name='check',
            name='VariableDeclaration',
        ),
        migrations.RemoveField(
            model_name='fbdtemplate',
            name='Jump',
        ),
        migrations.RemoveField(
            model_name='map',
            name='VariableDeclaration',
        ),
        migrations.RemoveField(
            model_name='rtu',
            name='SboVariables',
        ),
        migrations.RemoveField(
            model_name='rtu',
            name='VariableDeclaration',
        ),
        migrations.RemoveField(
            model_name='save',
            name='VariableDeclaration',
        ),
        migrations.RemoveField(
            model_name='sbo',
            name='FinalCheck',
        ),
        migrations.RemoveField(
            model_name='sbo',
            name='VariableDeclaration',
        ),
        migrations.AddField(
            model_name='check',
            name='Iterator',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='check',
            name='IteratorDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='check',
            name='LastValues',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='check',
            name='LastValuesDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='check',
            name='ST',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rtu',
            name='Action',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtu',
            name='ActionDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtu',
            name='CheckChanges',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtu',
            name='CheckChangesDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtu',
            name='Names',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtu',
            name='NamesDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtu',
            name='RiseChanges',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtu',
            name='RiseChangesDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtu',
            name='Saves',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtu',
            name='SavesDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtu',
            name='Signals',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtu',
            name='SignalsDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtu',
            name='TriggerChanges',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtu',
            name='TriggerChangesDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='Close',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='CloseDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='Delimiter',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='DelimiterDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='DelimiterInitVal',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='File',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='FileDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='Hysteresis',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='HysteresisDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='Iterator',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='IteratorDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='LastValues',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='LastValuesDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='NewLine',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='NewLineDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='NewLineInitVal',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='ObjectValue',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='ObjectValueDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='Offset',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='OffsetDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='PowerOnPrefix',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='PowerOnPrefixDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='PowerOnPrefixInitVal',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='Prefix',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='PrefixDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='PrefixUnderLine',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='PrefixUnderLineDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='PrefixUnderLineInitVal',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='Time',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='save',
            name='TimeDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sbo',
            name='ErrorStatInternal',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sbo',
            name='ErrorStatInternalDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sbo',
            name='Flag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sbo',
            name='FlagDataType',
            field=models.CharField(default='', max_length=255),
        ),
    ]
