# Generated by Django 2.1.5 on 2020-01-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0018_auto_20200130_2037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='STTemplate',
            new_name='FBTemplate',
        ),
    ]
