# Generated by Django 2.1.5 on 2020-01-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0019_auto_20200130_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprg',
            name='LocalRemoteState',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='LocalRemoteStateDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='MaskLocalRemote',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='MaskLocalRemoteDataType',
            field=models.CharField(default='', max_length=255),
        ),
    ]
