# Generated by Django 2.1.5 on 2020-02-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0023_auto_20200203_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprg',
            name='Version',
            field=models.CharField(default='', max_length=255),
        ),
    ]
