# Generated by Django 2.1.5 on 2020-02-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0024_auto_20200203_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtu',
            name='Version',
            field=models.CharField(default='', max_length=255),
        ),
    ]
