# Generated by Django 2.1.5 on 2020-02-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0025_auto_20200203_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='Prueba',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
