# Generated by Django 2.1.5 on 2020-02-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0026_pack_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='Prueba',
        ),
    ]
