# Generated by Django 2.1.5 on 2020-02-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0027_remove_pack_prueba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='TriggerState',
            new_name='RiseState',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='TriggerStateDataType',
            new_name='RiseStateDataType',
        ),
    ]
