# Generated by Django 2.1.5 on 2020-02-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0028_auto_20200203_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtu',
            name='Rise',
        ),
        migrations.RemoveField(
            model_name='rtu',
            name='RiseDataType',
        ),
    ]
