# Generated by Django 2.1.5 on 2020-02-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0030_auto_20200203_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtu',
            name='Error',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtu',
            name='ErrorDataType',
            field=models.CharField(default='', max_length=255),
        ),
    ]
