# Generated by Django 2.1.5 on 2020-02-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0031_auto_20200204_0912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FBTemplate',
        ),
        migrations.AddField(
            model_name='fbdtemplate',
            name='CodeEndTag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fbdtemplate',
            name='DeclarationAttributes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fbdtemplate',
            name='DeclarationEndTag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fbdtemplate',
            name='DeclarationFBHeader',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fbdtemplate',
            name='DeclarationFHeader',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fbdtemplate',
            name='DeclarationInput',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fbdtemplate',
            name='DeclarationInternal',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fbdtemplate',
            name='DeclarationOutput',
            field=models.TextField(default=''),
        ),
    ]
