# Generated by Django 2.1.5 on 2020-02-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0032_auto_20200204_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbdtemplate',
            name='FunctionOutputHeader',
            field=models.TextField(default=''),
        ),
    ]
