# Generated by Django 2.1.5 on 2020-02-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0033_fbdtemplate_functionoutputheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Version', models.CharField(max_length=255)),
                ('ErrorDescription', models.CharField(default='', max_length=255)),
                ('ErrorDescriptionDataType', models.CharField(default='', max_length=255)),
                ('ST', models.TextField(default='')),
            ],
        ),
    ]
