# Generated by Django 2.1.5 on 2020-02-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0035_auto_20200206_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprg',
            name='ProgramHeader',
            field=models.CharField(default='', max_length=255),
        ),
    ]
