# Generated by Django 2.1.5 on 2020-02-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0037_userprg_firstcycleinitval'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprg',
            name='ProgramEndTag',
            field=models.CharField(default='', max_length=255),
        ),
    ]
