# Generated by Django 2.1.5 on 2020-02-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0038_userprg_programendtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprg',
            name='LocRemState',
        ),
        migrations.RemoveField(
            model_name='userprg',
            name='LocRemStateDataType',
        ),
    ]
