# Generated by Django 2.1.5 on 2020-02-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0039_auto_20200209_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackLocRem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Version', models.CharField(max_length=255)),
                ('LocRemInput', models.CharField(default='', max_length=255)),
                ('LocRemInputDataType', models.CharField(default='', max_length=255)),
                ('LocRemOutput', models.CharField(default='', max_length=255)),
                ('LocRemOutputDataType', models.CharField(default='', max_length=255)),
                ('ST', models.TextField(default='')),
            ],
        ),
    ]
