# Generated by Django 2.1.5 on 2020-02-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0040_packlocrem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='StateLocRem',
        ),
        migrations.RemoveField(
            model_name='device',
            name='StateLocRemDataType',
        ),
        migrations.AddField(
            model_name='userprg',
            name='StateLocRem',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='StateLocRemDataType',
            field=models.CharField(default='', max_length=255),
        ),
    ]
