# Generated by Django 2.1.5 on 2020-02-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0042_checklocrem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbdtemplate',
            name='AssignInputHeader',
            field=models.TextField(default=''),
        ),
    ]
