# Generated by Django 2.1.5 on 2020-02-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0043_fbdtemplate_assigninputheader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={'verbose_name_plural': 'check'},
        ),
        migrations.AlterModelOptions(
            name='checklocrem',
            options={'verbose_name_plural': 'check_loc_rem'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name_plural': 'device'},
        ),
        migrations.AlterModelOptions(
            name='fbdtemplate',
            options={'verbose_name_plural': 'fbd_template'},
        ),
        migrations.AlterModelOptions(
            name='handler',
            options={'verbose_name_plural': 'handler'},
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name_plural': 'map'},
        ),
        migrations.AlterModelOptions(
            name='pack',
            options={'verbose_name_plural': 'pack'},
        ),
        migrations.AlterModelOptions(
            name='packlocrem',
            options={'verbose_name_plural': 'pack_loc_rem'},
        ),
        migrations.AlterModelOptions(
            name='risetotrigger',
            options={'verbose_name_plural': 'rise_to_trigger'},
        ),
        migrations.AlterModelOptions(
            name='rtu',
            options={'verbose_name_plural': 'rtu'},
        ),
        migrations.AlterModelOptions(
            name='save',
            options={'verbose_name_plural': 'save'},
        ),
        migrations.AlterModelOptions(
            name='sbo',
            options={'verbose_name_plural': 'sbo'},
        ),
        migrations.AlterModelOptions(
            name='userprg',
            options={'verbose_name_plural': 'user_prg'},
        ),
    ]
