# Generated by Django 2.1.5 on 2020-03-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesys', '0044_auto_20200217_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprg',
            name='DummyCommand',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='DummyCommandDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='DummyCommandOutput',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='DummyCommandOutputDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='DummyExecute',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='DummyExecuteDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='DummyMeasure',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='DummyMeasureDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='DummyMeasureOutput',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='DummyMeasureOutputDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='DummySelect',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='DummySelectDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='DummyState',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='DummyStateDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='DummyStateOutput',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='DummyStateOutputDataType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='DummyStatus',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprg',
            name='DummyStatusDataType',
            field=models.CharField(default='', max_length=255),
        ),
    ]
