# Generated by Django 2.1.5 on 2019-12-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.TextField(default='header')),
                ('ClosingTag', models.TextField(default='closing tag')),
            ],
        ),
    ]
