# Generated by Django 2.1.5 on 2020-02-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_parts', '0002_project_baseport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='BasePort',
        ),
    ]
