# Generated by Django 2.1.5 on 2019-12-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20191018_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='type',
        ),
        migrations.AddField(
            model_name='card',
            name='ControlIoa',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='card',
            name='ControlIoaJump',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='card',
            name='ControlObjectList',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='IO',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='card',
            name='MonitorIoa',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='card',
            name='MonitorIoaJump',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='card',
            name='MonitorObjectList',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='Name',
            field=models.CharField(default='DI16', max_length=255),
        ),
        migrations.AddField(
            model_name='card',
            name='Server',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3),
        ),
    ]
