# Generated by Django 2.1.5 on 2019-12-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20191204_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='ControlObjectList',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='MonitorObjectList',
            field=models.TextField(blank=True),
        ),
    ]
