# Generated by Django 2.1.5 on 2019-12-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20191204_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Server',
        ),
    ]
