# Generated by Django 2.1.5 on 2019-12-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_remove_card_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kbus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headers', models.TextField(default='')),
                ('ClosingTag', models.TextField(default='')),
                ('DI16', models.TextField(default='')),
                ('DO16', models.TextField(default='')),
            ],
        ),
    ]
