# Generated by Django 2.1.5 on 2019-12-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_kbus'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbus',
            name='FinalTerminal',
            field=models.TextField(default=''),
        ),
    ]
