# Generated by Django 2.1.5 on 2019-12-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_kbus_finalterminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='KbusInfo',
            field=models.TextField(default=''),
        ),
    ]
