# Generated by Django 2.1.5 on 2019-12-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_card_kbusinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kbus',
            name='DI16',
        ),
        migrations.RemoveField(
            model_name='kbus',
            name='DO16',
        ),
    ]
