# Generated by Django 2.1.5 on 2020-01-30 19:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_auto_20200130_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='ControlObjectList',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='MonitorObjectList',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, max_length=200),
        ),
    ]
