# Generated by Django 2.1.5 on 2020-02-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_auto_20200206_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='Protocol',
            field=models.CharField(choices=[('MODBUS_TCP', 'MODBUS_TCP'), ('IEC_103', 'IEC_103'), ('IEC_104', 'IEC_104')], default='104', max_length=255),
        ),
    ]
