# Generated by Django 2.1.5 on 2020-02-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_card_protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Protocol',
        ),
    ]
