# Generated by Django 2.1.5 on 2020-02-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_auto_20200211_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kbus',
            name='ClosingTag',
        ),
        migrations.RemoveField(
            model_name='kbus',
            name='FinalTerminal',
        ),
        migrations.RemoveField(
            model_name='kbus',
            name='Headers',
        ),
        migrations.AddField(
            model_name='kbus',
            name='Body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='kbus',
            name='DISignal',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='kbus',
            name='DOSignal',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='kbus',
            name='Terminal',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='IO',
            field=models.CharField(choices=[('DI', 'DI'), ('DO', 'DO')], default='', max_length=255),
        ),
    ]
