# Generated by Django 2.1.5 on 2020-02-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_auto_20200211_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbus',
            name='PrivateInputChannel',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='kbus',
            name='PrivateOutputChannel',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='kbus',
            name='PublicInputChannel',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='kbus',
            name='PublicOutputChannel',
            field=models.TextField(default=''),
        ),
    ]
